// Phase Shift — World 4: Entanglement
// Introduces entangled boxes — push in A, moves opposite in B
// TileType 4 = ENTANGLED_BOX, paired via entanglements array

import { LevelDefinition } from '../../types';

const F = 0, W = 1, E = 4, X = 5;

export const WORLD_04: LevelDefinition[] = [
    {
        id: '4-1', world: 4, level: 1, name: 'Linked',
        gridA: [
            [W,W,W,W,W,W],
            [W,F,F,F,F,W],
            [W,F,E,F,F,W],
            [W,F,F,F,F,W],
            [W,F,F,F,X,W],
            [W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W],
            [W,F,F,F,F,W],
            [W,F,F,E,F,W],
            [W,F,F,F,F,W],
            [W,X,F,F,F,W],
            [W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [4, 1],
        collapseCharges: 0,
        par: [5, 8, 12],
        entanglements: [{ idA: [2, 2], idB: [3, 2] }],
        tutorial: 'Entangled boxes (purple) are linked! Push one, and its partner moves in the OPPOSITE direction.',
    },
    {
        id: '4-2', world: 4, level: 2, name: 'Mirror Push',
        gridA: [
            [W,W,W,W,W,W],
            [W,F,F,F,F,W],
            [W,F,F,F,F,W],
            [W,F,E,F,F,W],
            [W,F,F,F,X,W],
            [W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W],
            [W,F,F,F,F,W],
            [W,F,F,F,F,W],
            [W,F,F,E,F,W],
            [W,X,F,F,F,W],
            [W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [4, 1],
        collapseCharges: 0,
        par: [5, 8, 12],
        entanglements: [{ idA: [2, 3], idB: [3, 3] }],
    },
    {
        id: '4-3', world: 4, level: 3, name: 'Entangled Path',
        gridA: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,F,E,F,F,W],
            [W,F,W,F,W,F,W],
            [W,F,F,F,F,X,W],
            [W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,F,F,E,F,W],
            [W,F,W,F,W,F,W],
            [W,X,F,F,F,F,W],
            [W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [5, 1],
        collapseCharges: 0,
        par: [6, 10, 15],
        entanglements: [{ idA: [3, 2], idB: [4, 2] }],
    },
    {
        id: '4-4', world: 4, level: 4, name: 'Two Pairs',
        gridA: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,E,F,F,F,W],
            [W,F,F,F,E,F,W],
            [W,F,F,F,F,X,W],
            [W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,F,F,E,F,W],
            [W,F,E,F,F,F,W],
            [W,X,F,F,F,F,W],
            [W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [5, 1],
        collapseCharges: 0,
        par: [7, 11, 16],
        entanglements: [
            { idA: [2, 2], idB: [4, 2] },
            { idA: [4, 3], idB: [2, 3] },
        ],
    },
    {
        id: '4-5', world: 4, level: 5, name: 'Squeeze Through',
        gridA: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,W,E,W,F,W],
            [W,F,F,F,F,F,W],
            [W,F,W,F,W,F,W],
            [W,F,F,F,F,X,W],
            [W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,W,F,W,F,W],
            [W,F,F,E,F,F,W],
            [W,F,W,F,W,F,W],
            [W,X,F,F,F,F,W],
            [W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [5, 1],
        collapseCharges: 0,
        par: [7, 11, 16],
        entanglements: [{ idA: [3, 2], idB: [3, 3] }],
    },
    {
        id: '4-6', world: 4, level: 6, name: 'Entangled Walls',
        gridA: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,E,W,F,F,W],
            [W,F,F,F,F,F,W],
            [W,W,F,F,F,F,W],
            [W,F,F,F,F,X,W],
            [W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,F,W,E,F,W],
            [W,F,F,F,F,F,W],
            [W,F,F,F,F,W,W],
            [W,X,F,F,F,F,W],
            [W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [5, 1],
        collapseCharges: 0,
        par: [7, 12, 17],
        entanglements: [{ idA: [2, 2], idB: [4, 2] }],
    },
    {
        id: '4-7', world: 4, level: 7, name: 'Box and Chain',
        gridA: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,2,F,E,F,W],
            [W,F,F,F,F,F,W],
            [W,F,F,F,F,X,W],
            [W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,E,F,2,F,W],
            [W,F,F,F,F,F,W],
            [W,X,F,F,F,F,W],
            [W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [5, 1],
        collapseCharges: 0,
        par: [6, 10, 15],
        entanglements: [{ idA: [4, 2], idB: [2, 2] }],
        tutorial: 'Regular boxes (gold) and entangled boxes (purple) can coexist. Plan pushes carefully!',
    },
    {
        id: '4-8', world: 4, level: 8, name: 'Inverse Motion',
        gridA: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,F,E,F,F,W],
            [W,F,F,F,F,F,W],
            [W,F,W,F,W,F,W],
            [W,F,F,F,F,X,W],
            [W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,F,F,F,F,W],
            [W,F,F,E,F,F,W],
            [W,F,W,F,W,F,W],
            [W,X,F,F,F,F,W],
            [W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [5, 1],
        collapseCharges: 0,
        par: [7, 11, 16],
        entanglements: [{ idA: [3, 2], idB: [3, 3] }],
    },
    {
        id: '4-9', world: 4, level: 9, name: 'Entangled Maze',
        gridA: [
            [W,W,W,W,W,W,W,W],
            [W,F,F,F,F,F,F,W],
            [W,F,W,E,W,F,F,W],
            [W,F,F,F,F,F,F,W],
            [W,F,W,F,W,E,F,W],
            [W,F,F,F,F,F,X,W],
            [W,W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W,W],
            [W,F,F,F,F,F,F,W],
            [W,F,F,W,F,E,W,W],
            [W,F,F,F,F,F,F,W],
            [W,F,E,W,F,W,F,W],
            [W,X,F,F,F,F,F,W],
            [W,W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [6, 1],
        collapseCharges: 0,
        par: [9, 14, 20],
        entanglements: [
            { idA: [3, 2], idB: [5, 2] },
            { idA: [5, 4], idB: [2, 4] },
        ],
    },
    {
        id: '4-10', world: 4, level: 10, name: 'Tight Entangle',
        gridA: [
            [W,W,W,W,W,W],
            [W,F,F,F,F,W],
            [W,F,E,F,F,W],
            [W,W,F,W,F,W],
            [W,F,F,F,X,W],
            [W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W],
            [W,F,F,F,F,W],
            [W,F,F,E,F,W],
            [W,F,W,F,W,W],
            [W,X,F,F,F,W],
            [W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [4, 1],
        collapseCharges: 0,
        par: [6, 9, 13],
        entanglements: [{ idA: [2, 2], idB: [3, 2] }],
    },
    {
        id: '4-11', world: 4, level: 11, name: 'Push Chain',
        gridA: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,E,F,2,F,W],
            [W,F,F,F,F,F,W],
            [W,F,2,F,E,F,W],
            [W,F,F,F,F,X,W],
            [W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,2,F,E,F,W],
            [W,F,F,F,F,F,W],
            [W,F,E,F,2,F,W],
            [W,X,F,F,F,F,W],
            [W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [5, 1],
        collapseCharges: 0,
        par: [8, 13, 18],
        entanglements: [
            { idA: [2, 2], idB: [4, 2] },
            { idA: [4, 4], idB: [2, 4] },
        ],
    },
    {
        id: '4-12', world: 4, level: 12, name: 'Corner Entangle',
        gridA: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,F,F,W,F,W],
            [W,F,F,E,F,F,W],
            [W,F,W,F,F,F,W],
            [W,F,F,F,F,X,W],
            [W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,W,F,F,F,W],
            [W,F,F,E,F,F,W],
            [W,F,F,F,W,F,W],
            [W,X,F,F,F,F,W],
            [W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [5, 1],
        collapseCharges: 0,
        par: [7, 11, 16],
        entanglements: [{ idA: [3, 3], idB: [3, 3] }],
    },
    {
        id: '4-13', world: 4, level: 13, name: 'Three Boxes',
        gridA: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,E,F,2,F,W],
            [W,F,F,F,F,F,W],
            [W,F,2,F,E,F,W],
            [W,F,F,2,F,X,W],
            [W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,2,F,E,F,W],
            [W,F,F,F,F,F,W],
            [W,F,E,F,2,F,W],
            [W,X,2,F,F,F,W],
            [W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [5, 1],
        collapseCharges: 0,
        par: [9, 14, 20],
        entanglements: [
            { idA: [2, 2], idB: [4, 2] },
            { idA: [4, 4], idB: [2, 4] },
        ],
    },
    {
        id: '4-14', world: 4, level: 14, name: 'Wall Bounce',
        gridA: [
            [W,W,W,W,W,W,W,W],
            [W,F,F,F,F,F,F,W],
            [W,F,E,W,F,F,F,W],
            [W,F,F,F,F,W,F,W],
            [W,F,W,F,F,F,F,W],
            [W,F,F,F,F,F,X,W],
            [W,W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W,W],
            [W,F,F,F,F,F,F,W],
            [W,F,F,F,W,E,F,W],
            [W,F,W,F,F,F,F,W],
            [W,F,F,F,F,W,F,W],
            [W,X,F,F,F,F,F,W],
            [W,W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [6, 1],
        collapseCharges: 0,
        par: [8, 13, 18],
        entanglements: [{ idA: [2, 2], idB: [5, 2] }],
    },
    {
        id: '4-15', world: 4, level: 15, name: 'Pincer',
        gridA: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,E,F,E,F,W],
            [W,F,F,W,F,F,W],
            [W,F,F,F,F,F,W],
            [W,F,F,F,F,X,W],
            [W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,E,F,E,F,W],
            [W,F,F,W,F,F,W],
            [W,F,F,F,F,F,W],
            [W,X,F,F,F,F,W],
            [W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [5, 1],
        collapseCharges: 0,
        par: [8, 12, 18],
        entanglements: [
            { idA: [2, 2], idB: [4, 2] },
            { idA: [4, 2], idB: [2, 2] },
        ],
    },
    {
        id: '4-16', world: 4, level: 16, name: 'Entangled Cross',
        gridA: [
            [W,W,W,W,W,W,W],
            [W,F,F,E,F,F,W],
            [W,F,W,F,W,F,W],
            [W,E,F,F,F,E,W],
            [W,F,W,F,W,F,W],
            [W,F,F,F,F,X,W],
            [W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W],
            [W,F,F,E,F,F,W],
            [W,F,W,F,W,F,W],
            [W,E,F,F,F,E,W],
            [W,F,W,F,W,F,W],
            [W,X,F,F,F,F,W],
            [W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [5, 1],
        collapseCharges: 0,
        par: [9, 14, 20],
        entanglements: [
            { idA: [3, 1], idB: [3, 1] },
            { idA: [1, 3], idB: [5, 3] },
            { idA: [5, 3], idB: [1, 3] },
        ],
    },
    {
        id: '4-17', world: 4, level: 17, name: 'Parallel Lines',
        gridA: [
            [W,W,W,W,W,W,W,W],
            [W,F,F,F,F,F,F,W],
            [W,F,E,F,F,E,F,W],
            [W,F,F,W,W,F,F,W],
            [W,F,F,F,F,F,F,W],
            [W,F,F,F,F,F,X,W],
            [W,W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W,W],
            [W,F,F,F,F,F,F,W],
            [W,F,E,F,F,E,F,W],
            [W,F,F,W,W,F,F,W],
            [W,F,F,F,F,F,F,W],
            [W,X,F,F,F,F,F,W],
            [W,W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [6, 1],
        collapseCharges: 0,
        par: [9, 14, 20],
        entanglements: [
            { idA: [2, 2], idB: [5, 2] },
            { idA: [5, 2], idB: [2, 2] },
        ],
    },
    {
        id: '4-18', world: 4, level: 18, name: 'Dense Entangle',
        gridA: [
            [W,W,W,W,W,W,W,W],
            [W,F,F,F,F,F,F,W],
            [W,F,E,F,2,F,F,W],
            [W,F,F,W,F,F,F,W],
            [W,F,2,F,E,F,F,W],
            [W,F,F,F,F,F,X,W],
            [W,W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W,W],
            [W,F,F,F,F,F,F,W],
            [W,F,F,2,F,E,F,W],
            [W,F,F,F,W,F,F,W],
            [W,F,F,E,F,2,F,W],
            [W,X,F,F,F,F,F,W],
            [W,W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [6, 1],
        collapseCharges: 0,
        par: [10, 16, 22],
        entanglements: [
            { idA: [2, 2], idB: [5, 2] },
            { idA: [4, 4], idB: [3, 4] },
        ],
    },
    {
        id: '4-19', world: 4, level: 19, name: 'Entangled Gauntlet',
        gridA: [
            [W,W,W,W,W,W,W,W],
            [W,F,F,F,F,F,F,W],
            [W,F,E,W,F,E,F,W],
            [W,F,F,F,F,F,F,W],
            [W,F,W,F,W,F,F,W],
            [W,F,F,E,F,F,X,W],
            [W,W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W,W],
            [W,F,F,F,F,F,F,W],
            [W,F,E,F,W,E,F,W],
            [W,F,F,F,F,F,F,W],
            [W,F,F,W,F,W,F,W],
            [W,X,F,E,F,F,F,W],
            [W,W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [6, 1],
        collapseCharges: 0,
        par: [10, 16, 22],
        entanglements: [
            { idA: [2, 2], idB: [5, 2] },
            { idA: [5, 2], idB: [2, 2] },
            { idA: [3, 5], idB: [3, 5] },
        ],
    },
    {
        id: '4-20', world: 4, level: 20, name: 'Entanglement Mastered',
        gridA: [
            [W,W,W,W,W,W,W,W],
            [W,F,F,F,F,F,F,W],
            [W,F,E,W,F,E,F,W],
            [W,F,F,F,F,F,F,W],
            [W,F,W,2,W,F,F,W],
            [W,F,F,F,F,E,F,W],
            [W,F,F,F,F,F,X,W],
            [W,W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W,W],
            [W,F,F,F,F,F,F,W],
            [W,F,E,F,W,E,F,W],
            [W,F,F,F,F,F,F,W],
            [W,F,F,W,2,W,F,W],
            [W,F,E,F,F,F,F,W],
            [W,X,F,F,F,F,F,W],
            [W,W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [6, 1],
        collapseCharges: 0,
        par: [12, 18, 26],
        entanglements: [
            { idA: [2, 2], idB: [5, 2] },
            { idA: [5, 2], idB: [2, 2] },
            { idA: [5, 5], idB: [2, 5] },
        ],
        tutorial: 'World 4 complete! Superposition (Phase Gates + Entanglement) awaits...',
    },
];
