// Phase Shift — World 7: Collapse
// Introduces the Collapse mechanic — temporarily move in only one dimension
// Collapse pickups (6) give charges. Q/E to collapse into dim A/B.

import { LevelDefinition } from '../../types';

const F = 0, W = 1, BX = 2, X = 5, CP = 6;

export const WORLD_07: LevelDefinition[] = [
    { id: '7-1', world: 7, level: 1, name: 'First Collapse',
        gridA: [[W,W,W,W,W,W],[W,F,F,F,F,W],[W,F,F,F,F,W],[W,F,F,F,F,W],[W,F,F,F,X,W],[W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W],[W,F,F,F,F,W],[W,F,W,W,F,W],[W,F,F,F,F,W],[W,X,F,F,F,W],[W,W,W,W,W,W]],
        startA: [1,1], startB: [4,1], collapseCharges: 1, par: [5,8,12],
        tutorial: 'Press Q to collapse into Dim A (move only in A). Press E for Dim B. Press Q/E again to uncollapse. You have limited charges!',
    },
    { id: '7-2', world: 7, level: 2, name: 'Split Move',
        gridA: [[W,W,W,W,W,W],[W,F,F,F,F,W],[W,F,W,F,F,W],[W,F,F,F,F,W],[W,F,F,F,X,W],[W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W],[W,F,F,F,F,W],[W,F,F,W,F,W],[W,F,F,F,F,W],[W,X,F,F,F,W],[W,W,W,W,W,W]],
        startA: [1,1], startB: [4,1], collapseCharges: 1, par: [6,9,13],
    },
    { id: '7-3', world: 7, level: 3, name: 'Pickup',
        gridA: [[W,W,W,W,W,W],[W,F,F,CP,F,W],[W,F,W,F,F,W],[W,F,F,F,F,W],[W,F,F,F,X,W],[W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W],[W,F,F,CP,F,W],[W,F,F,W,F,W],[W,F,F,F,F,W],[W,X,F,F,F,W],[W,W,W,W,W,W]],
        startA: [1,1], startB: [4,1], collapseCharges: 0, par: [6,10,14],
        tutorial: 'Yellow diamonds are Collapse Pickups. Walk over them to gain collapse charges!',
    },
    { id: '7-4', world: 7, level: 4, name: 'Two Collapses',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,W,F,W,F,W],[W,F,F,F,F,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,F,W,F,W,W],[W,F,F,F,F,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 2, par: [7,11,16],
    },
    { id: '7-5', world: 7, level: 5, name: 'Strategic Collapse',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,W,W,F,F,F,W],[W,F,F,F,F,F,W],[W,F,F,F,W,W,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,F,F,W,W,W],[W,F,F,F,F,F,W],[W,W,W,F,F,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 2, par: [8,12,18],
    },
    { id: '7-6', world: 7, level: 6, name: 'Collapse and Box',
        gridA: [[W,W,W,W,W,W],[W,F,F,F,F,W],[W,F,BX,F,F,W],[W,F,F,W,F,W],[W,F,F,F,X,W],[W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W],[W,F,F,F,F,W],[W,F,F,BX,F,W],[W,F,W,F,F,W],[W,X,F,F,F,W],[W,W,W,W,W,W]],
        startA: [1,1], startB: [4,1], collapseCharges: 1, par: [7,11,16],
    },
    { id: '7-7', world: 7, level: 7, name: 'Precise Collapse',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,W,F,W,F,W],[W,F,F,F,F,F,W],[W,F,W,F,W,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,F,W,F,W,W],[W,F,F,F,F,F,W],[W,W,F,W,F,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 2, par: [9,14,20],
    },
    { id: '7-8', world: 7, level: 8, name: 'Pickup Chain',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,CP,F,W,F,W],[W,F,F,F,F,F,W],[W,F,W,F,CP,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,W,F,CP,F,W],[W,F,F,F,F,F,W],[W,F,CP,F,W,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 0, par: [9,14,20],
    },
    { id: '7-9', world: 7, level: 9, name: 'Collapse Maze',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,W,F,W,F,F,W],[W,F,F,F,F,F,F,W],[W,F,F,W,F,W,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,F,W,F,W,F,W],[W,F,F,F,F,F,F,W],[W,F,W,F,W,F,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 3, par: [10,16,22],
    },
    { id: '7-10', world: 7, level: 10, name: 'Tight Budget',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,W,F,W,F,F,W],[W,F,F,F,F,W,W],[W,F,W,F,F,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,F,W,F,W,W],[W,W,W,F,F,F,W],[W,F,F,F,W,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 1, par: [9,14,20],
        tutorial: 'Only 1 collapse charge! Use it at exactly the right moment.',
    },
    { id: '7-11', world: 7, level: 11, name: 'Box and Collapse',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,BX,F,F,F,W],[W,F,F,W,BX,F,W],[W,F,F,F,F,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,F,F,BX,F,W],[W,F,BX,W,F,F,W],[W,F,F,F,F,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 2, par: [9,14,20],
    },
    { id: '7-12', world: 7, level: 12, name: 'Asymmetric Collapse',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,W,W,F,F,F,W],[W,F,F,F,F,W,F,W],[W,F,F,W,F,F,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,F,F,W,W,F,W],[W,F,W,F,F,F,F,W],[W,F,F,F,W,F,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [10,16,22],
    },
    { id: '7-13', world: 7, level: 13, name: 'Collapse Corridor',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,W,F,W,F,W,F,W],[W,F,F,F,F,F,F,W],[W,F,W,F,W,F,W,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,W,F,W,F,W,W],[W,F,F,F,F,F,F,W],[W,W,F,W,F,W,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 3, par: [10,16,22],
    },
    { id: '7-14', world: 7, level: 14, name: 'Collapse Sprint',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,W,F,F,F,W],[W,F,F,W,F,F,W],[W,F,F,F,W,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,F,F,W,F,W],[W,F,F,W,F,F,W],[W,F,W,F,F,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 2, par: [8,12,18],
    },
    { id: '7-15', world: 7, level: 15, name: 'Multi Collapse',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,W,F,F,W,F,W],[W,F,F,F,F,F,F,W],[W,F,F,W,F,F,W,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,F,W,F,F,W,W],[W,F,F,F,F,F,F,W],[W,F,W,F,F,W,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 3, par: [10,16,22],
    },
    { id: '7-16', world: 7, level: 16, name: 'Collapse with Pickup',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,W,CP,F,F,W],[W,F,F,W,F,F,W],[W,F,F,F,W,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,F,CP,W,F,W],[W,F,F,W,F,F,W],[W,F,W,F,F,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 1, par: [9,14,20],
    },
    { id: '7-17', world: 7, level: 17, name: 'Collapse Box Relay',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,BX,W,F,F,F,W],[W,F,F,F,F,BX,F,W],[W,F,F,W,F,F,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,F,F,W,BX,F,W],[W,F,BX,F,F,F,F,W],[W,F,F,F,W,F,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [10,16,22],
    },
    { id: '7-18', world: 7, level: 18, name: 'Collapse Expert',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,W,F,W,F,W,F,W],[W,F,F,F,F,F,F,W],[W,F,W,F,W,F,W,W],[W,F,F,F,F,F,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,W,F,W,F,W,W],[W,F,F,F,F,F,F,W],[W,W,F,W,F,W,F,W],[W,F,F,F,F,F,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 3, par: [12,18,26],
    },
    { id: '7-19', world: 7, level: 19, name: 'Collapse Gauntlet',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,W,F,W,F,F,W],[W,F,F,W,F,F,F,W],[W,F,W,F,F,W,F,W],[W,F,F,F,W,F,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,F,W,F,W,F,W],[W,F,F,F,W,F,F,W],[W,F,W,F,F,W,F,W],[W,F,F,W,F,F,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 3, par: [14,20,28],
    },
    { id: '7-20', world: 7, level: 20, name: 'Collapse Mastered',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,W,F,W,F,F,W,W],[W,F,F,F,BX,F,F,W],[W,F,W,F,W,F,F,W],[W,F,F,F,F,F,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,W,W,F,F,W,F,W],[W,F,F,BX,F,F,F,W],[W,F,F,W,F,W,F,W],[W,F,F,F,F,F,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 3, par: [14,22,30],
        tutorial: 'World 7 complete! Full mastery puzzles await...',
    },
];
