// Phase Shift — World 10: Singularity
// The ultimate challenge — brain-melting puzzles using every mechanic

import { LevelDefinition } from '../../types';

const F = 0, W = 1, BX = 2, E = 4, X = 5, CP = 6, I = 7, GA = 30, GB = 31;

export const WORLD_10: LevelDefinition[] = [
    { id: '10-1', world: 10, level: 1, name: 'Event Horizon',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,F,I,GB,F,W],[W,F,E,W,F,F,F,W],[W,F,I,F,BX,I,F,W],[W,F,F,W,F,E,F,W],[W,F,GB,I,F,GA,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,I,F,GA,F,W],[W,F,F,F,W,E,F,W],[W,F,I,BX,F,I,F,W],[W,F,E,W,F,F,F,W],[W,X,GA,F,I,GB,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [14,22,30],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '10-2', world: 10, level: 2, name: 'Gravitational',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,GA,I,GB,F,W],[W,F,E,F,W,F,CP,W],[W,F,I,F,E,F,F,W],[W,CP,F,W,F,E,F,W],[W,F,GB,I,GA,F,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,I,GA,F,F,W],[W,CP,F,W,F,E,F,W],[W,F,F,E,F,I,F,W],[W,F,E,F,W,F,CP,W],[W,F,F,GA,I,GB,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [18,26,36],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[4,3],idB:[3,3]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '10-3', world: 10, level: 3, name: 'Spaghettification',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,I,I,GB,F,W],[W,F,E,F,W,F,F,W],[W,F,F,W,F,F,F,W],[W,F,F,F,W,E,F,W],[W,F,GB,I,I,GA,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,I,I,GA,F,W],[W,F,F,W,F,E,F,W],[W,F,F,F,W,F,F,W],[W,F,E,F,F,W,F,W],[W,X,GA,I,I,GB,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 3, par: [14,22,30],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '10-4', world: 10, level: 4, name: 'Tidal Force',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,F,GB,F,GA,W],[W,F,E,W,F,I,F,W],[W,F,F,F,E,F,F,W],[W,F,I,F,W,E,F,W],[W,GB,F,GA,F,GB,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,GB,F,GA,F,GB,F,W],[W,F,I,F,W,E,F,W],[W,F,F,E,F,F,F,W],[W,F,E,W,F,I,F,W],[W,X,GA,F,GB,F,GA,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [14,22,30],
        entanglements: [{idA:[2,2],idB:[5,2]},{idA:[4,3],idB:[3,3]},{idA:[5,4],idB:[2,4]}],
    },
    { id: '10-5', world: 10, level: 5, name: 'Schwarzschild',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,I,F,GB,F,W],[W,F,E,W,BX,F,F,W],[W,F,I,F,F,I,CP,W],[W,F,F,BX,W,E,F,W],[W,F,GB,F,I,GA,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,F,I,GA,F,W],[W,F,F,BX,W,E,F,W],[W,CP,I,F,F,I,F,W],[W,F,E,W,BX,F,F,W],[W,F,GA,I,F,GB,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [20,30,40],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '10-6', world: 10, level: 6, name: 'Penrose',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,F,I,F,GB,W],[W,F,F,E,W,F,F,W],[W,F,I,F,F,I,F,W],[W,F,F,W,E,F,F,W],[W,GB,F,I,F,GA,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,GB,F,I,F,GA,F,W],[W,F,F,W,E,F,F,W],[W,F,I,F,F,I,F,W],[W,F,E,F,W,F,F,W],[W,F,GA,F,I,F,GB,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 3, par: [16,24,34],
        entanglements: [{idA:[3,2],idB:[4,4]},{idA:[4,4],idB:[3,2]}],
    },
    { id: '10-7', world: 10, level: 7, name: 'Hawking',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,I,F,GB,F,W],[W,F,E,W,CP,F,F,W],[W,F,I,F,E,I,F,W],[W,F,F,CP,W,E,F,W],[W,F,GB,I,F,GA,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,F,I,GA,F,W],[W,F,F,CP,W,E,F,W],[W,F,I,E,F,I,F,W],[W,F,E,W,CP,F,F,W],[W,F,GA,I,F,GB,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [18,28,38],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[4,3],idB:[3,3]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '10-8', world: 10, level: 8, name: 'Information Paradox',
        gridA: [[W,W,W,W,W,W,W,W,W],[W,F,GA,F,I,F,GB,F,W],[W,F,E,W,F,F,F,F,W],[W,F,F,F,BX,F,I,F,W],[W,F,F,W,F,F,F,F,W],[W,F,I,F,F,BX,F,F,W],[W,F,F,F,W,F,E,F,W],[W,F,GB,F,I,F,GA,X,W],[W,W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W,W],[W,F,GB,F,I,F,GA,F,W],[W,F,F,F,W,F,E,F,W],[W,F,I,F,F,BX,F,F,W],[W,F,F,F,W,F,F,F,W],[W,F,F,BX,F,F,I,F,W],[W,F,E,W,F,F,F,F,W],[W,X,GA,F,I,F,GB,F,W],[W,W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [7,1], collapseCharges: 2, par: [20,30,42],
        entanglements: [{idA:[2,2],idB:[6,6]},{idA:[6,6],idB:[2,2]}],
    },
    { id: '10-9', world: 10, level: 9, name: 'Kerr',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,I,F,GB,F,W],[W,F,E,W,F,I,CP,W],[W,F,I,F,E,F,F,W],[W,CP,I,F,W,E,F,W],[W,F,GB,F,I,GA,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,F,I,GA,F,W],[W,CP,I,F,W,E,F,W],[W,F,F,E,F,I,F,W],[W,F,E,W,F,I,CP,W],[W,F,GA,I,F,GB,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [20,30,42],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[4,3],idB:[3,3]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '10-10', world: 10, level: 10, name: 'Wormhole',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,I,F,GB,F,W],[W,F,E,W,F,F,F,W],[W,F,I,F,E,I,F,W],[W,F,F,W,F,E,F,W],[W,F,GB,F,I,GA,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,F,I,GA,F,W],[W,F,F,F,W,E,F,W],[W,F,I,E,F,I,F,W],[W,F,E,W,F,F,F,W],[W,F,GA,I,F,GB,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 3, par: [16,24,34],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[4,3],idB:[3,3]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '10-11', world: 10, level: 11, name: 'Accretion',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,I,F,GB,F,W],[W,F,E,W,BX,F,F,W],[W,F,I,F,F,I,F,W],[W,F,F,BX,W,E,F,W],[W,F,GB,I,F,GA,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,F,I,GA,F,W],[W,F,F,BX,W,E,F,W],[W,F,I,F,F,I,F,W],[W,F,E,W,BX,F,F,W],[W,F,GA,I,F,GB,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [18,28,38],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '10-12', world: 10, level: 12, name: 'Photon Sphere',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,GA,I,GB,F,W],[W,F,E,I,W,F,F,W],[W,F,I,F,F,I,F,W],[W,F,F,W,I,E,F,W],[W,F,GB,I,GA,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,I,GA,F,F,W],[W,F,F,W,I,E,F,W],[W,F,I,F,F,I,F,W],[W,F,E,I,W,F,F,W],[W,X,GA,I,GB,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [14,22,30],
        entanglements: [{idA:[2,2],idB:[4,4]},{idA:[4,4],idB:[2,2]}],
    },
    { id: '10-13', world: 10, level: 13, name: 'Ergosphere',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,I,F,GB,F,W],[W,F,E,W,CP,F,F,W],[W,F,I,F,E,I,F,W],[W,F,F,CP,W,E,F,W],[W,F,GB,F,I,GA,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,F,I,GA,F,W],[W,F,F,CP,W,E,F,W],[W,F,I,E,F,I,F,W],[W,F,E,W,CP,F,F,W],[W,F,GA,I,F,GB,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [20,30,42],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[4,3],idB:[3,3]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '10-14', world: 10, level: 14, name: 'Planck Scale',
        gridA: [[W,W,W,W,W,W,W,W,W],[W,F,GA,F,I,F,GB,F,W],[W,F,E,W,F,CP,F,F,W],[W,F,I,F,E,F,I,F,W],[W,F,F,F,W,F,F,F,W],[W,F,I,F,E,F,I,F,W],[W,F,F,CP,W,F,E,F,W],[W,F,GB,F,I,F,GA,X,W],[W,W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W,W],[W,F,GB,F,I,F,GA,F,W],[W,F,F,CP,W,F,E,F,W],[W,F,I,F,E,F,I,F,W],[W,F,F,F,F,W,F,F,W],[W,F,I,F,E,F,I,F,W],[W,F,E,W,F,CP,F,F,W],[W,X,GA,F,I,F,GB,F,W],[W,W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [7,1], collapseCharges: 0, par: [22,34,46],
        entanglements: [{idA:[2,2],idB:[6,6]},{idA:[4,3],idB:[4,5]},{idA:[6,6],idB:[2,2]}],
    },
    { id: '10-15', world: 10, level: 15, name: 'Grand Unification',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,I,F,GB,F,W],[W,F,E,W,BX,F,CP,W],[W,F,I,F,E,I,F,W],[W,CP,F,BX,W,E,F,W],[W,F,GB,I,F,GA,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,F,I,GA,F,W],[W,CP,F,BX,W,E,F,W],[W,F,I,E,F,I,F,W],[W,F,E,W,BX,F,CP,W],[W,F,GA,I,F,GB,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [22,34,46],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[4,3],idB:[3,3]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '10-16', world: 10, level: 16, name: 'String Theory',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,F,I,GB,F,W],[W,F,E,W,F,F,F,W],[W,F,I,F,E,I,F,W],[W,F,F,W,F,E,F,W],[W,F,GB,F,I,GA,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,I,F,GA,F,W],[W,F,F,F,W,E,F,W],[W,F,I,E,F,I,F,W],[W,F,E,W,F,F,F,W],[W,F,GA,F,I,GB,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [16,24,34],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[4,3],idB:[3,3]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '10-17', world: 10, level: 17, name: 'Multiverse',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,I,F,GB,F,W],[W,F,E,W,BX,I,CP,W],[W,F,I,F,E,F,F,W],[W,CP,I,BX,W,E,F,W],[W,F,GB,F,I,GA,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,F,I,GA,F,W],[W,CP,I,BX,W,E,F,W],[W,F,F,E,F,I,F,W],[W,F,E,W,BX,I,CP,W],[W,F,GA,I,F,GB,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [22,34,48],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[4,3],idB:[3,3]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '10-18', world: 10, level: 18, name: 'Theory of Everything',
        gridA: [[W,W,W,W,W,W,W,W,W],[W,F,GA,F,I,F,GB,F,W],[W,F,E,W,F,BX,F,F,W],[W,F,I,F,E,F,I,CP,W],[W,F,F,F,W,F,F,F,W],[W,CP,I,F,E,F,I,F,W],[W,F,F,BX,W,F,E,F,W],[W,F,GB,F,I,F,GA,X,W],[W,W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W,W],[W,F,GB,F,I,F,GA,F,W],[W,F,F,BX,W,F,E,F,W],[W,CP,I,F,E,F,I,F,W],[W,F,F,F,F,W,F,F,W],[W,F,I,F,E,F,I,CP,W],[W,F,E,W,F,BX,F,F,W],[W,X,GA,F,I,F,GB,F,W],[W,W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [7,1], collapseCharges: 0, par: [24,36,50],
        entanglements: [{idA:[2,2],idB:[6,6]},{idA:[4,3],idB:[4,5]},{idA:[6,6],idB:[2,2]}],
    },
    { id: '10-19', world: 10, level: 19, name: 'Singularity',
        gridA: [[W,W,W,W,W,W,W,W,W],[W,F,GA,I,F,GB,F,F,W],[W,F,E,W,BX,F,CP,F,W],[W,F,I,F,E,I,F,F,W],[W,F,F,F,W,F,F,F,W],[W,F,I,E,F,I,F,F,W],[W,CP,F,BX,W,F,E,F,W],[W,F,GB,F,I,GA,F,X,W],[W,W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W,W],[W,F,GB,F,I,GA,F,F,W],[W,CP,F,BX,W,E,F,F,W],[W,F,I,E,F,I,F,F,W],[W,F,F,F,F,W,F,F,W],[W,F,I,F,E,I,F,F,W],[W,F,E,W,BX,F,CP,F,W],[W,X,GA,I,F,GB,F,F,W],[W,W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [7,1], collapseCharges: 0, par: [26,40,54],
        entanglements: [{idA:[2,2],idB:[6,6]},{idA:[4,3],idB:[4,5]},{idA:[6,6],idB:[2,2]}],
    },
    { id: '10-20', world: 10, level: 20, name: 'Unified Field',
        gridA: [[W,W,W,W,W,W,W,W,W],[W,F,GA,I,F,GB,F,F,W],[W,F,E,W,BX,F,CP,F,W],[W,F,I,F,E,I,F,F,W],[W,CP,F,BX,W,F,F,F,W],[W,F,I,E,F,I,F,F,W],[W,F,F,W,BX,F,E,F,W],[W,F,GB,I,F,GA,F,X,W],[W,W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W,W],[W,F,GB,F,I,GA,F,F,W],[W,F,F,BX,W,E,CP,F,W],[W,F,I,E,F,I,F,F,W],[W,F,F,F,W,BX,F,CP,W],[W,F,I,F,E,I,F,F,W],[W,F,E,W,F,BX,F,F,W],[W,X,GA,I,F,GB,F,F,W],[W,W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [7,1], collapseCharges: 0, par: [28,42,58],
        entanglements: [{idA:[2,2],idB:[6,6]},{idA:[4,3],idB:[4,5]},{idA:[6,6],idB:[2,2]}],
        tutorial: 'Congratulations! You have mastered Phase Shift. You are one with the quantum.',
    },
];
