// Phase Shift — World 6: Interference
// Combines Phase Gates + Entanglement in harder configurations
// Also introduces ice tiles (7)

import { LevelDefinition } from '../../types';

const F = 0, W = 1, BX = 2, E = 4, X = 5, I = 7, GA = 30, GB = 31;

export const WORLD_06: LevelDefinition[] = [
    { id: '6-1', world: 6, level: 1, name: 'Ice Introduction',
        gridA: [[W,W,W,W,W,W],[W,F,F,F,F,W],[W,F,I,I,F,W],[W,F,F,F,F,W],[W,F,F,F,X,W],[W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W],[W,F,F,F,F,W],[W,F,F,F,F,W],[W,F,I,I,F,W],[W,X,F,F,F,W],[W,W,W,W,W,W]],
        startA: [1,1], startB: [4,1], collapseCharges: 0, par: [4,7,10],
        tutorial: 'Ice tiles (light blue) make you slide until you hit something! Plan your slides.',
    },
    { id: '6-2', world: 6, level: 2, name: 'Slide Path',
        gridA: [[W,W,W,W,W,W],[W,F,F,F,F,W],[W,F,I,I,I,W],[W,F,F,F,F,W],[W,F,F,F,X,W],[W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W],[W,F,F,F,F,W],[W,F,F,F,F,W],[W,I,I,I,F,W],[W,X,F,F,F,W],[W,W,W,W,W,W]],
        startA: [1,1], startB: [4,1], collapseCharges: 0, par: [5,8,12],
    },
    { id: '6-3', world: 6, level: 3, name: 'Ice and Gates',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,I,GA,I,F,W],[W,F,F,F,F,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,I,GA,I,F,W],[W,F,F,F,F,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 0, par: [6,10,14],
    },
    { id: '6-4', world: 6, level: 4, name: 'Ice Box',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,BX,I,I,F,W],[W,F,F,F,F,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,I,I,BX,F,W],[W,F,F,F,F,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 0, par: [6,10,15],
    },
    { id: '6-5', world: 6, level: 5, name: 'Slide Entangle',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,E,I,F,F,W],[W,F,F,F,F,F,W],[W,F,I,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,F,I,E,F,W],[W,F,F,F,F,F,W],[W,X,F,F,I,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 0, par: [7,11,16],
        entanglements: [{idA:[2,2],idB:[4,2]}],
    },
    { id: '6-6', world: 6, level: 6, name: 'Gate Slide',
        gridA: [[W,W,W,W,W,W,W],[W,F,GA,F,F,F,W],[W,F,I,I,I,F,W],[W,F,F,F,GB,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,GB,F,W],[W,F,I,I,I,F,W],[W,F,GA,F,F,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 0, par: [7,11,16],
    },
    { id: '6-7', world: 6, level: 7, name: 'Triple Threat',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,GA,E,I,F,W],[W,F,F,W,F,F,W],[W,F,I,E,GB,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,GB,I,E,F,W],[W,F,F,W,F,F,W],[W,F,E,I,GA,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 0, par: [8,13,18],
        entanglements: [{idA:[3,2],idB:[4,2]},{idA:[3,4],idB:[2,4]}],
    },
    { id: '6-8', world: 6, level: 8, name: 'Friction',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,I,I,GA,F,F,W],[W,F,F,E,F,F,F,W],[W,F,F,GB,I,I,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,F,GB,I,I,F,W],[W,F,F,E,F,F,F,W],[W,F,I,I,GA,F,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [9,14,20],
        entanglements: [{idA:[3,3],idB:[3,3]}],
    },
    { id: '6-9', world: 6, level: 9, name: 'Ice Channel',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,I,I,I,I,F,W],[W,F,F,W,F,W,F,W],[W,F,GA,F,GB,F,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,I,I,I,I,F,W],[W,F,W,F,W,F,F,W],[W,F,GB,F,GA,F,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [8,13,18],
    },
    { id: '6-10', world: 6, level: 10, name: 'Entangled Ice',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,E,I,F,F,W],[W,F,F,W,F,F,W],[W,F,F,I,E,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,F,I,E,F,W],[W,F,F,W,F,F,W],[W,F,E,I,F,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 0, par: [8,13,18],
        entanglements: [{idA:[2,2],idB:[4,2]},{idA:[4,4],idB:[2,4]}],
    },
    { id: '6-11', world: 6, level: 11, name: 'Slippery Gate',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,I,GA,F,F,F,W],[W,F,F,F,F,I,F,W],[W,F,GB,F,W,F,F,W],[W,F,F,F,F,F,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,GB,I,F,F,W],[W,F,I,F,F,F,F,W],[W,F,F,F,W,GA,F,W],[W,F,F,F,F,F,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [8,13,18],
    },
    { id: '6-12', world: 6, level: 12, name: 'Cross Ice',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,I,F,F,W],[W,F,F,F,F,F,W],[W,I,F,W,F,I,W],[W,F,F,F,F,F,W],[W,F,F,I,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,I,F,W],[W,F,F,F,F,F,W],[W,F,I,W,I,F,W],[W,F,F,F,F,F,W],[W,X,I,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 0, par: [8,12,18],
    },
    { id: '6-13', world: 6, level: 13, name: 'Full Combo',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,F,I,F,F,W],[W,F,E,W,F,GB,F,W],[W,F,F,F,F,F,F,W],[W,F,I,F,W,E,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,I,F,GB,F,W],[W,F,GB,F,W,E,F,W],[W,F,F,F,F,F,F,W],[W,F,E,W,F,I,F,W],[W,X,F,F,F,GA,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [10,16,22],
        entanglements: [{idA:[2,2],idB:[5,2]},{idA:[5,4],idB:[2,4]}],
    },
    { id: '6-14', world: 6, level: 14, name: 'Ice Maze',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,I,F,F,F,W],[W,F,W,F,W,I,F,W],[W,F,I,F,F,F,F,W],[W,F,F,W,I,W,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,I,F,F,W],[W,F,I,W,F,W,F,W],[W,F,F,F,I,F,F,W],[W,F,W,I,F,W,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [10,16,22],
    },
    { id: '6-15', world: 6, level: 15, name: 'Quantum Slide',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,I,I,F,F,W],[W,F,F,F,F,F,F,W],[W,F,E,W,F,GB,F,W],[W,F,F,F,F,F,F,W],[W,F,I,I,GA,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,F,I,I,F,W],[W,F,F,F,F,F,F,W],[W,F,GA,F,W,E,F,W],[W,F,F,F,F,F,F,W],[W,X,GB,I,I,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [10,16,22],
        entanglements: [{idA:[2,3],idB:[5,3]}],
    },
    { id: '6-16', world: 6, level: 16, name: 'Convergence',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,GA,F,F,W],[W,F,I,F,I,F,W],[W,F,F,E,F,F,W],[W,F,I,F,I,F,W],[W,F,F,GB,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,GB,F,F,W],[W,F,I,F,I,F,W],[W,F,F,E,F,F,W],[W,F,I,F,I,F,W],[W,X,GA,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 0, par: [9,14,20],
        entanglements: [{idA:[3,3],idB:[3,3]}],
    },
    { id: '6-17', world: 6, level: 17, name: 'Box Slide Gate',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,BX,I,GA,F,F,W],[W,F,F,F,F,F,F,W],[W,F,GA,I,BX,F,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,F,GA,I,BX,F,W],[W,F,F,F,F,F,F,W],[W,F,BX,I,GA,F,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [10,16,22],
    },
    { id: '6-18', world: 6, level: 18, name: 'All Mechanics',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,F,I,F,F,W],[W,F,E,W,F,GB,F,W],[W,F,I,F,BX,F,F,W],[W,F,GB,F,W,E,F,W],[W,F,F,I,F,GA,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,F,F,I,F,W],[W,F,F,E,W,GA,F,W],[W,F,F,BX,F,I,F,W],[W,F,E,W,F,GB,F,W],[W,X,GA,I,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [12,18,26],
        entanglements: [{idA:[2,2],idB:[3,2]},{idA:[5,4],idB:[2,4]}],
    },
    { id: '6-19', world: 6, level: 19, name: 'Interference Wave',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,F,GB,F,GA,W],[W,F,I,E,F,I,F,W],[W,F,F,W,F,F,F,W],[W,F,I,F,E,I,F,W],[W,F,GB,F,GA,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,GB,F,GA,F,GB,F,W],[W,F,I,F,E,I,F,W],[W,F,F,F,W,F,F,W],[W,F,I,E,F,I,F,W],[W,X,GA,F,GB,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [12,18,26],
        entanglements: [{idA:[3,2],idB:[4,2]},{idA:[4,4],idB:[3,4]}],
    },
    { id: '6-20', world: 6, level: 20, name: 'Interference Mastery',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,I,F,GB,F,W],[W,F,E,W,F,I,F,W],[W,F,I,F,E,F,F,W],[W,F,GB,W,I,GA,F,W],[W,F,F,E,F,F,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,F,I,GA,F,W],[W,F,I,E,W,F,F,W],[W,F,F,E,F,I,F,W],[W,F,GA,I,W,GB,F,W],[W,F,E,F,F,F,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [14,22,30],
        entanglements: [{idA:[2,2],idB:[3,2]},{idA:[4,3],idB:[3,3]},{idA:[3,5],idB:[2,5]}],
        tutorial: 'World 6 complete! Collapse mechanic awaits...',
    },
];
