// Phase Shift — World 8: Decoherence
// Full mastery — combines all mechanics: gates, entanglement, collapse, ice, boxes

import { LevelDefinition } from '../../types';

const F = 0, W = 1, BX = 2, E = 4, X = 5, CP = 6, I = 7, GA = 30, GB = 31;

export const WORLD_08: LevelDefinition[] = [
    { id: '8-1', world: 8, level: 1, name: 'Warm Up',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,GA,F,F,W],[W,F,E,F,F,F,W],[W,F,F,W,F,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,GA,F,F,W],[W,F,F,F,E,F,W],[W,F,F,W,F,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 1, par: [6,10,14],
        entanglements: [{idA:[2,2],idB:[4,2]}],
    },
    { id: '8-2', world: 8, level: 2, name: 'Gate Collapse',
        gridA: [[W,W,W,W,W,W,W],[W,F,GA,F,F,F,W],[W,F,F,E,F,F,W],[W,F,F,W,GB,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,GA,F,W],[W,F,F,E,F,F,W],[W,F,GB,W,F,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 1, par: [7,11,16],
        entanglements: [{idA:[3,2],idB:[3,2]}],
    },
    { id: '8-3', world: 8, level: 3, name: 'Ice Collapse',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,I,I,F,F,W],[W,F,F,W,F,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,F,I,I,F,W],[W,F,F,W,F,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 1, par: [6,10,14],
    },
    { id: '8-4', world: 8, level: 4, name: 'Triple Mix',
        gridA: [[W,W,W,W,W,W,W],[W,F,GA,F,F,F,W],[W,F,E,I,F,F,W],[W,F,F,W,GB,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,GA,F,W],[W,F,F,I,E,F,W],[W,F,GB,W,F,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 1, par: [7,12,17],
        entanglements: [{idA:[2,2],idB:[4,2]}],
    },
    { id: '8-5', world: 8, level: 5, name: 'Pickup Path',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,CP,W,F,GA,F,W],[W,F,F,F,F,F,F,W],[W,F,GA,F,W,CP,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,GA,F,W,CP,F,W],[W,F,F,F,F,F,F,W],[W,F,CP,W,F,GA,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [10,16,22],
    },
    { id: '8-6', world: 8, level: 6, name: 'Entangled Ice',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,E,I,F,F,W],[W,F,F,W,F,F,W],[W,F,I,F,E,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,F,I,E,F,W],[W,F,F,W,F,F,W],[W,F,E,F,I,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 1, par: [8,13,18],
        entanglements: [{idA:[2,2],idB:[4,2]},{idA:[4,4],idB:[2,4]}],
    },
    { id: '8-7', world: 8, level: 7, name: 'Phase Slide',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,I,I,GB,F,W],[W,F,F,F,F,F,F,W],[W,F,E,W,F,F,F,W],[W,F,F,F,F,F,F,W],[W,F,GB,I,I,GA,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,I,I,GA,F,W],[W,F,F,F,F,F,F,W],[W,F,F,F,W,E,F,W],[W,F,F,F,F,F,F,W],[W,X,GA,I,I,GB,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 1, par: [10,16,22],
        entanglements: [{idA:[2,3],idB:[5,3]}],
    },
    { id: '8-8', world: 8, level: 8, name: 'All In',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,F,I,F,F,W],[W,F,E,F,W,GB,F,W],[W,F,F,BX,F,F,F,W],[W,F,GB,F,W,E,F,W],[W,F,F,I,F,GA,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,I,F,GA,F,W],[W,F,GB,W,F,E,F,W],[W,F,F,F,BX,F,F,W],[W,F,E,W,F,GB,F,W],[W,X,GA,F,I,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [12,18,26],
        entanglements: [{idA:[2,2],idB:[5,2]},{idA:[5,4],idB:[2,4]}],
    },
    { id: '8-9', world: 8, level: 9, name: 'Precision',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,GA,E,W,I,F,W],[W,F,F,F,F,F,F,W],[W,F,I,W,E,GB,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,I,W,E,GA,F,W],[W,F,F,F,F,F,F,W],[W,F,GB,E,W,I,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [10,16,22],
        entanglements: [{idA:[3,2],idB:[4,2]},{idA:[4,4],idB:[3,4]}],
    },
    { id: '8-10', world: 8, level: 10, name: 'Cascade',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,GA,F,F,F,W],[W,F,E,F,I,GB,F,W],[W,F,F,W,F,F,F,W],[W,F,GB,I,F,E,F,W],[W,F,F,F,GA,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,GB,F,F,W],[W,F,F,E,I,GA,F,W],[W,F,F,F,W,F,F,W],[W,F,GA,F,I,E,F,W],[W,X,F,GB,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [12,18,26],
        entanglements: [{idA:[2,2],idB:[3,2]},{idA:[5,4],idB:[4,4]}],
    },
    { id: '8-11', world: 8, level: 11, name: 'Deep Thought',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,F,I,F,F,W],[W,F,F,E,W,F,F,W],[W,F,I,F,F,GB,F,W],[W,F,F,W,E,F,F,W],[W,F,F,F,I,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,I,F,GA,F,W],[W,F,F,W,E,F,F,W],[W,F,GB,F,F,I,F,W],[W,F,F,E,W,F,F,W],[W,X,F,I,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [12,18,26],
        entanglements: [{idA:[3,2],idB:[4,2]},{idA:[4,4],idB:[3,4]}],
    },
    { id: '8-12', world: 8, level: 12, name: 'Quantum Relay',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,GA,E,F,CP,F,W],[W,F,F,W,F,F,F,W],[W,F,CP,F,E,GB,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,CP,F,E,GA,F,W],[W,F,F,F,W,F,F,W],[W,F,GB,E,F,CP,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [12,18,26],
        entanglements: [{idA:[3,2],idB:[4,2]},{idA:[4,4],idB:[3,4]}],
    },
    { id: '8-13', world: 8, level: 13, name: 'Box Slide Gate',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,BX,I,GA,F,F,W],[W,F,F,F,F,F,F,W],[W,F,GA,I,BX,F,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,F,GA,I,BX,F,W],[W,F,F,F,F,F,F,W],[W,F,BX,I,GA,F,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 1, par: [10,16,22],
    },
    { id: '8-14', world: 8, level: 14, name: 'Decoherence',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,F,I,GB,F,W],[W,F,E,W,F,F,F,W],[W,F,F,BX,F,CP,F,W],[W,F,F,W,E,F,F,W],[W,F,GB,I,F,GA,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,I,F,GA,F,W],[W,F,F,F,W,E,F,W],[W,F,CP,F,BX,F,F,W],[W,F,E,W,F,F,F,W],[W,X,GA,F,I,GB,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 1, par: [14,22,30],
        entanglements: [{idA:[2,2],idB:[5,2]},{idA:[4,4],idB:[2,4]}],
    },
    { id: '8-15', world: 8, level: 15, name: 'Momentum',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,I,I,F,F,W],[W,F,GA,F,F,E,F,W],[W,F,F,W,F,F,F,W],[W,F,E,F,F,GB,F,W],[W,F,F,I,I,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,I,I,F,W],[W,F,E,F,F,GA,F,W],[W,F,F,F,W,F,F,W],[W,F,GB,F,F,E,F,W],[W,X,I,I,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [12,18,26],
        entanglements: [{idA:[5,2],idB:[2,4]},{idA:[2,4],idB:[5,2]}],
    },
    { id: '8-16', world: 8, level: 16, name: 'Entropy',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,GA,F,GB,F,W],[W,F,E,F,W,F,F,W],[W,F,I,F,F,I,F,W],[W,F,F,W,F,E,F,W],[W,F,GB,F,GA,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,F,GA,F,F,W],[W,F,F,E,F,W,F,W],[W,F,I,F,F,I,F,W],[W,F,W,F,E,F,F,W],[W,X,GA,F,GB,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [12,18,26],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '8-17', world: 8, level: 17, name: 'Wave Function',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,F,I,F,GB,W],[W,F,F,E,W,F,F,W],[W,F,I,F,F,I,F,W],[W,F,F,W,E,F,F,W],[W,F,GB,F,I,F,GA,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,GB,F,I,F,GA,F,W],[W,F,F,W,E,F,F,W],[W,F,I,F,F,I,F,W],[W,F,E,W,F,F,F,W],[W,GA,F,I,F,GB,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [14,22,30],
        entanglements: [{idA:[3,2],idB:[4,2]},{idA:[4,4],idB:[3,4]}],
    },
    { id: '8-18', world: 8, level: 18, name: 'Observer Effect',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,GA,F,F,F,W],[W,F,E,I,F,GB,F,W],[W,F,F,W,BX,F,F,W],[W,F,GB,F,I,E,F,W],[W,F,F,GA,F,F,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,GB,F,F,W],[W,F,GB,F,I,E,F,W],[W,F,F,BX,W,F,F,W],[W,F,E,I,F,GA,F,W],[W,F,F,F,GA,F,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [14,22,30],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '8-19', world: 8, level: 19, name: 'Schrodinger',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,F,I,GB,F,W],[W,F,E,W,F,F,CP,W],[W,F,F,F,E,F,F,W],[W,CP,F,F,W,E,F,W],[W,F,GB,I,F,GA,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,I,F,GA,F,W],[W,CP,F,F,W,E,F,W],[W,F,F,E,F,F,F,W],[W,F,E,W,F,F,CP,W],[W,F,GA,F,I,GB,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [16,24,32],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[4,3],idB:[3,3]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '8-20', world: 8, level: 20, name: 'Decoherence Mastery',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,F,I,GB,F,W],[W,F,E,W,F,F,F,W],[W,F,I,F,BX,F,CP,W],[W,F,F,W,F,E,F,W],[W,F,GB,I,F,GA,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,I,F,GA,F,W],[W,F,F,F,W,E,F,W],[W,CP,F,BX,F,I,F,W],[W,F,E,W,F,F,F,W],[W,F,GA,F,I,GB,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 1, par: [16,24,34],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[5,4],idB:[2,2]}],
        tutorial: 'World 8 complete! The Quantum Leap awaits...',
    },
];
