// Phase Shift — World 9: Quantum Leap
// Expert puzzles combining all mechanics at higher difficulty

import { LevelDefinition } from '../../types';

const F = 0, W = 1, BX = 2, E = 4, X = 5, CP = 6, I = 7, GA = 30, GB = 31;

export const WORLD_09: LevelDefinition[] = [
    { id: '9-1', world: 9, level: 1, name: 'Quantum Step',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,F,F,GB,F,W],[W,F,F,E,W,I,F,W],[W,F,I,F,F,F,F,W],[W,F,W,F,E,F,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,F,F,GA,F,W],[W,F,I,W,E,F,F,W],[W,F,F,F,F,I,F,W],[W,F,F,E,F,W,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [10,16,22],
        entanglements: [{idA:[3,2],idB:[4,2]},{idA:[4,4],idB:[3,4]}],
    },
    { id: '9-2', world: 9, level: 2, name: 'Phase Entangle',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,GA,I,F,F,W],[W,F,E,F,W,GB,F,W],[W,F,F,F,F,F,F,W],[W,F,GB,W,F,E,F,W],[W,F,I,GA,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,I,GA,F,F,W],[W,F,GB,W,F,E,F,W],[W,F,F,F,F,F,F,W],[W,F,E,F,W,GB,F,W],[W,X,GA,I,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [12,18,26],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '9-3', world: 9, level: 3, name: 'Ice Gate Slide',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,GA,I,I,F,W],[W,F,F,F,W,F,F,W],[W,F,I,I,GB,F,F,W],[W,F,F,F,F,F,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,I,I,GB,F,F,W],[W,F,F,W,F,F,F,W],[W,F,F,GA,I,I,F,W],[W,F,F,F,F,F,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 1, par: [8,14,20],
    },
    { id: '9-4', world: 9, level: 4, name: 'Collapse Strategy',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,W,E,F,GA,F,W],[W,F,F,F,W,F,F,W],[W,F,GA,F,E,W,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,GA,F,E,W,F,W],[W,F,F,W,F,F,F,W],[W,F,W,E,F,GA,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [10,16,22],
        entanglements: [{idA:[3,2],idB:[4,2]},{idA:[4,4],idB:[3,4]}],
    },
    { id: '9-5', world: 9, level: 5, name: 'Quantum Bridge',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,F,I,GB,F,W],[W,F,E,W,F,F,F,W],[W,F,F,BX,F,I,F,W],[W,F,F,W,F,E,F,W],[W,F,GB,I,F,GA,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,I,F,GA,F,W],[W,F,F,F,W,E,F,W],[W,F,I,F,BX,F,F,W],[W,F,E,W,F,F,F,W],[W,X,GA,F,I,GB,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [14,22,30],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '9-6', world: 9, level: 6, name: 'Interference II',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,GA,F,GB,F,W],[W,F,E,I,W,F,F,W],[W,F,F,F,F,F,F,W],[W,F,F,W,I,E,F,W],[W,F,GB,F,GA,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,F,GA,F,F,W],[W,F,F,W,I,E,F,W],[W,F,F,F,F,F,F,W],[W,F,E,I,W,F,F,W],[W,X,GA,F,GB,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [12,18,26],
        entanglements: [{idA:[2,2],idB:[4,4]},{idA:[4,4],idB:[2,2]}],
    },
    { id: '9-7', world: 9, level: 7, name: 'Heisenberg',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,I,F,F,GB,W],[W,F,E,F,W,F,F,W],[W,F,F,F,BX,F,F,W],[W,F,F,W,F,E,F,W],[W,GB,F,F,I,GA,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,GB,F,F,I,GA,F,W],[W,F,F,W,F,E,F,W],[W,F,F,BX,F,F,F,W],[W,F,E,F,W,F,F,W],[W,F,GA,I,F,F,GB,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [14,22,30],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '9-8', world: 9, level: 8, name: 'Entangled Slide',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,I,I,F,F,W],[W,F,E,F,F,GA,F,W],[W,F,F,W,F,F,F,W],[W,F,GA,F,F,E,F,W],[W,F,F,I,I,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,I,I,F,W],[W,F,GA,F,F,E,F,W],[W,F,F,F,W,F,F,W],[W,F,E,F,F,GA,F,W],[W,X,I,I,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [12,18,26],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '9-9', world: 9, level: 9, name: 'Pickup Expert',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,F,I,F,F,W],[W,F,E,W,F,CP,F,W],[W,F,F,F,F,F,F,W],[W,F,CP,F,W,E,F,W],[W,F,F,I,F,GA,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,I,F,GA,F,W],[W,F,CP,F,W,E,F,W],[W,F,F,F,F,F,F,W],[W,F,E,W,F,CP,F,W],[W,X,GA,F,I,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [14,22,30],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '9-10', world: 9, level: 10, name: 'Tunnel Vision',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,GA,F,GB,F,W],[W,F,I,F,W,I,F,W],[W,F,F,E,F,F,F,W],[W,F,I,W,F,I,F,W],[W,F,GB,F,GA,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,F,GA,F,F,W],[W,F,I,W,F,I,F,W],[W,F,F,F,E,F,F,W],[W,F,I,F,W,I,F,W],[W,X,GA,F,GB,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [12,18,26],
        entanglements: [{idA:[3,3],idB:[4,3]}],
    },
    { id: '9-11', world: 9, level: 11, name: 'Pulse',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,I,F,GB,F,W],[W,F,E,F,W,F,F,W],[W,F,I,F,BX,I,F,W],[W,F,F,W,F,E,F,W],[W,F,GB,F,I,GA,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,F,I,GA,F,W],[W,F,F,W,F,E,F,W],[W,F,I,BX,F,I,F,W],[W,F,E,F,W,F,F,W],[W,X,GA,I,F,GB,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [14,22,30],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '9-12', world: 9, level: 12, name: 'Wave Collapse',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,F,GA,F,F,W],[W,F,E,I,F,GB,F,W],[W,F,F,W,F,F,F,W],[W,F,GB,F,I,E,F,W],[W,F,F,GA,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,GA,F,F,F,W],[W,F,GB,F,I,E,F,W],[W,F,F,F,W,F,F,W],[W,F,E,I,F,GB,F,W],[W,X,F,F,GA,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 3, par: [14,22,30],
        entanglements: [{idA:[2,2],idB:[4,4]},{idA:[4,4],idB:[2,2]}],
    },
    { id: '9-13', world: 9, level: 13, name: 'Quantum Lock',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,F,I,GB,F,W],[W,F,E,W,F,F,CP,W],[W,F,F,F,E,F,F,W],[W,CP,F,F,W,E,F,W],[W,F,GB,I,F,GA,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,I,F,GA,F,W],[W,CP,F,F,W,E,F,W],[W,F,F,E,F,F,F,W],[W,F,E,W,F,F,CP,W],[W,F,GA,F,I,GB,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [16,24,34],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[4,3],idB:[3,3]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '9-14', world: 9, level: 14, name: 'Superflow',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,I,GA,I,F,W],[W,F,E,F,W,F,F,W],[W,F,F,GB,F,F,F,W],[W,F,F,W,F,E,F,W],[W,F,I,GA,I,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,I,GA,I,F,F,W],[W,F,F,W,F,E,F,W],[W,F,F,F,GB,F,F,W],[W,F,E,F,W,F,F,W],[W,X,F,I,GA,I,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [12,18,26],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '9-15', world: 9, level: 15, name: 'Phase Matrix',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,F,GB,F,GA,W],[W,F,E,W,F,E,F,W],[W,F,F,F,F,F,F,W],[W,F,E,F,W,E,F,W],[W,GB,F,GA,F,GB,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,GB,F,GA,F,GB,F,W],[W,F,E,F,W,E,F,W],[W,F,F,F,F,F,F,W],[W,F,E,W,F,E,F,W],[W,X,GA,F,GB,F,GA,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [14,22,30],
        entanglements: [{idA:[2,2],idB:[5,2]},{idA:[5,2],idB:[2,2]},{idA:[2,4],idB:[5,4]},{idA:[5,4],idB:[2,4]}],
    },
    { id: '9-16', world: 9, level: 16, name: 'Quantum Knot',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,I,F,GB,F,W],[W,F,E,F,W,F,F,W],[W,F,I,F,E,I,F,W],[W,F,F,W,F,E,F,W],[W,F,GB,F,I,GA,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,F,I,GA,F,W],[W,F,F,W,F,E,F,W],[W,F,I,E,F,I,F,W],[W,F,E,F,W,F,F,W],[W,X,GA,I,F,GB,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [14,22,30],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[4,3],idB:[3,3]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '9-17', world: 9, level: 17, name: 'Leap',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,GA,I,GB,F,W],[W,F,E,W,F,F,F,W],[W,F,I,F,BX,F,F,W],[W,F,F,W,F,E,F,W],[W,F,GB,I,GA,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,I,GA,F,F,W],[W,F,F,F,W,E,F,W],[W,F,F,BX,F,I,F,W],[W,F,E,W,F,F,F,W],[W,X,GA,I,GB,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 2, par: [14,22,30],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '9-18', world: 9, level: 18, name: 'Probability',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,F,I,F,GB,W],[W,F,E,W,F,CP,F,W],[W,F,F,BX,F,F,F,W],[W,F,CP,F,W,E,F,W],[W,GB,F,I,F,GA,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,GB,F,I,F,GA,F,W],[W,F,CP,F,W,E,F,W],[W,F,F,F,BX,F,F,W],[W,F,E,W,F,CP,F,W],[W,F,GA,F,I,F,GB,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [18,26,36],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '9-19', world: 9, level: 19, name: 'Quantum Leap',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,I,F,GB,F,W],[W,F,E,W,F,F,CP,W],[W,F,I,F,E,I,F,W],[W,CP,F,W,F,E,F,W],[W,F,GB,F,I,GA,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,F,I,GA,F,W],[W,CP,F,F,W,E,F,W],[W,F,I,E,F,I,F,W],[W,F,E,W,F,F,CP,W],[W,F,GA,I,F,GB,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [18,28,38],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[4,3],idB:[3,3]},{idA:[5,4],idB:[2,2]}],
    },
    { id: '9-20', world: 9, level: 20, name: 'Quantum Leap Mastery',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,GA,I,F,GB,F,W],[W,F,E,W,BX,F,CP,W],[W,F,I,F,E,I,F,W],[W,CP,F,W,F,E,F,W],[W,F,GB,I,F,GA,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,GB,F,I,GA,F,W],[W,CP,F,BX,W,E,F,W],[W,F,I,E,F,I,F,W],[W,F,E,W,F,F,CP,W],[W,F,GA,I,F,GB,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [20,30,40],
        entanglements: [{idA:[2,2],idB:[5,4]},{idA:[4,3],idB:[3,3]},{idA:[5,4],idB:[2,2]}],
        tutorial: 'World 9 complete! The Singularity — final world — awaits...',
    },
];
