// Phase Shift — World 5: Superposition
// Combines Phase Gates + Entanglement

import { LevelDefinition } from '../../types';

const F = 0, W = 1, E = 4, X = 5, A = 30, B = 31;

export const WORLD_05: LevelDefinition[] = [
    { id: '5-1', world: 5, level: 1, name: 'Combo Intro',
        gridA: [[W,W,W,W,W,W],[W,F,F,A,F,W],[W,F,E,F,F,W],[W,F,F,F,F,W],[W,F,F,F,X,W],[W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W],[W,F,F,A,F,W],[W,F,F,E,F,W],[W,F,F,F,F,W],[W,X,F,F,F,W],[W,W,W,W,W,W]],
        startA: [1,1], startB: [4,1], collapseCharges: 0, par: [5,8,12],
        entanglements: [{idA:[2,2],idB:[3,2]}],
        tutorial: 'Phase gates AND entangled boxes together. Think in both dimensions!',
    },
    { id: '5-2', world: 5, level: 2, name: 'Gate Guard',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,E,B,F,F,W],[W,F,F,F,F,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,F,B,E,F,W],[W,F,F,F,F,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 0, par: [6,10,15],
        entanglements: [{idA:[2,2],idB:[4,2]}],
    },
    { id: '5-3', world: 5, level: 3, name: 'Phase Push',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,A,E,F,F,W],[W,F,F,F,F,F,W],[W,F,F,B,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,F,E,A,F,W],[W,F,F,F,F,F,W],[W,X,F,B,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 0, par: [7,11,16],
        entanglements: [{idA:[3,2],idB:[3,2]}],
    },
    { id: '5-4', world: 5, level: 4, name: 'Filtered Path',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,A,W,F,W,B,W],[W,F,F,E,F,F,W],[W,B,W,F,W,A,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,A,W,F,W,B,W],[W,F,F,E,F,F,W],[W,B,W,F,W,A,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 0, par: [8,12,18],
        entanglements: [{idA:[3,3],idB:[3,3]}],
    },
    { id: '5-5', world: 5, level: 5, name: 'Gate Entangle',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,E,A,F,F,W],[W,F,F,F,F,F,W],[W,F,A,F,E,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,F,A,E,F,W],[W,F,F,F,F,F,W],[W,F,E,F,A,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 0, par: [8,12,18],
        entanglements: [{idA:[2,2],idB:[4,2]},{idA:[4,4],idB:[2,4]}],
    },
    { id: '5-6', world: 5, level: 6, name: 'Dimension Lock',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,B,F,E,F,W],[W,F,F,W,F,F,W],[W,F,E,F,B,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,B,F,E,F,W],[W,F,F,W,F,F,W],[W,F,E,F,B,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 0, par: [8,13,18],
        entanglements: [{idA:[4,2],idB:[2,4]},{idA:[2,4],idB:[4,2]}],
    },
    { id: '5-7', world: 5, level: 7, name: 'Phase Tunnel',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,A,F,B,F,W],[W,F,W,F,W,F,F,W],[W,F,E,F,F,F,F,W],[W,F,W,F,W,F,F,W],[W,F,F,B,F,A,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,B,F,A,F,W],[W,F,F,W,F,W,F,W],[W,F,F,F,E,F,F,W],[W,F,F,W,F,W,F,W],[W,X,A,F,B,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [9,14,20],
        entanglements: [{idA:[2,3],idB:[4,3]}],
    },
    { id: '5-8', world: 5, level: 8, name: 'Overlap',
        gridA: [[W,W,W,W,W,W,W],[W,F,A,F,F,F,W],[W,F,F,E,F,F,W],[W,F,F,F,F,F,W],[W,F,F,F,B,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,B,F,W],[W,F,F,E,F,F,W],[W,F,F,F,F,F,W],[W,F,A,F,F,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 0, par: [7,11,16],
        entanglements: [{idA:[3,2],idB:[3,2]}],
    },
    { id: '5-9', world: 5, level: 9, name: 'Double Filter',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,A,F,B,F,W],[W,F,E,F,W,F,E,W],[W,F,F,F,F,F,F,W],[W,F,W,F,2,F,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,B,F,A,F,F,W],[W,E,F,W,F,E,F,W],[W,F,F,F,F,F,F,W],[W,F,F,2,F,W,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [10,16,22],
        entanglements: [{idA:[2,2],idB:[5,2]},{idA:[6,2],idB:[1,2]}],
    },
    { id: '5-10', world: 5, level: 10, name: 'Interference',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,A,E,B,F,W],[W,F,F,W,F,F,W],[W,F,B,E,A,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,B,E,A,F,W],[W,F,F,W,F,F,W],[W,F,A,E,B,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 0, par: [9,14,20],
        entanglements: [{idA:[3,2],idB:[3,4]},{idA:[3,4],idB:[3,2]}],
    },
    { id: '5-11', world: 5, level: 11, name: 'Quantum Walk',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,A,F,F,B,F,W],[W,F,F,E,W,F,F,W],[W,F,W,F,F,F,F,W],[W,F,F,F,W,E,F,W],[W,F,B,F,F,A,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,B,F,F,A,F,W],[W,F,F,W,E,F,F,W],[W,F,F,F,F,W,F,W],[W,F,E,W,F,F,F,W],[W,X,A,F,F,B,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [10,16,22],
        entanglements: [{idA:[3,2],idB:[4,2]},{idA:[5,4],idB:[2,4]}],
    },
    { id: '5-12', world: 5, level: 12, name: 'Interlocked',
        gridA: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,A,E,F,F,W],[W,F,E,W,A,F,W],[W,F,F,F,F,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,F,F,F,F,W],[W,F,F,E,A,F,W],[W,F,A,W,E,F,W],[W,F,F,F,F,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 0, par: [8,13,18],
        entanglements: [{idA:[3,2],idB:[3,2]},{idA:[2,3],idB:[4,3]}],
    },
    { id: '5-13', world: 5, level: 13, name: 'Phase Lock',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,A,E,W,B,F,W],[W,F,F,F,F,F,F,W],[W,F,B,W,E,A,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,B,W,E,A,F,W],[W,F,F,F,F,F,F,W],[W,F,A,E,W,B,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [10,16,22],
        entanglements: [{idA:[3,2],idB:[4,2]},{idA:[4,4],idB:[3,4]}],
    },
    { id: '5-14', world: 5, level: 14, name: 'Weave',
        gridA: [[W,W,W,W,W,W,W],[W,F,A,F,B,F,W],[W,F,F,E,F,F,W],[W,F,B,W,A,F,W],[W,F,F,E,F,F,W],[W,F,F,F,F,X,W],[W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W],[W,F,B,F,A,F,W],[W,F,F,E,F,F,W],[W,F,A,W,B,F,W],[W,F,F,E,F,F,W],[W,X,F,F,F,F,W],[W,W,W,W,W,W,W]],
        startA: [1,1], startB: [5,1], collapseCharges: 0, par: [9,14,20],
        entanglements: [{idA:[3,2],idB:[3,4]},{idA:[3,4],idB:[3,2]}],
    },
    { id: '5-15', world: 5, level: 15, name: 'Phase Relay',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,A,E,F,B,F,W],[W,F,F,W,F,F,F,W],[W,F,B,F,E,A,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,F,F,F,F,W],[W,F,B,F,E,A,F,W],[W,F,F,F,W,F,F,W],[W,F,A,E,F,B,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [10,16,22],
        entanglements: [{idA:[3,2],idB:[4,2]},{idA:[4,4],idB:[3,4]}],
    },
    { id: '5-16', world: 5, level: 16, name: 'Quantum Maze',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,F,A,F,F,F,W],[W,F,E,W,F,B,F,W],[W,F,F,F,F,F,F,W],[W,F,B,F,W,E,F,W],[W,F,F,F,A,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,F,B,F,F,F,W],[W,F,F,W,E,A,F,W],[W,F,F,F,F,F,F,W],[W,F,A,E,F,W,F,W],[W,X,F,B,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [10,16,22],
        entanglements: [{idA:[2,2],idB:[4,2]},{idA:[5,4],idB:[3,4]}],
    },
    { id: '5-17', world: 5, level: 17, name: 'Triple Gate',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,A,F,B,F,A,W],[W,F,F,E,F,E,F,W],[W,F,W,F,W,F,F,W],[W,F,F,F,F,F,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,B,F,A,F,B,F,W],[W,F,E,F,E,F,F,W],[W,F,F,W,F,W,F,W],[W,F,F,F,F,F,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [10,16,22],
        entanglements: [{idA:[3,2],idB:[4,2]},{idA:[5,2],idB:[2,2]}],
    },
    { id: '5-18', world: 5, level: 18, name: 'Full Spectrum',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,A,F,B,F,F,W],[W,F,E,W,F,E,F,W],[W,F,F,F,F,F,F,W],[W,F,E,F,W,B,F,W],[W,F,B,F,A,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,B,F,A,F,F,W],[W,F,F,E,W,E,F,W],[W,F,F,F,F,F,F,W],[W,F,B,W,F,E,F,W],[W,X,A,F,B,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [12,18,26],
        entanglements: [{idA:[2,2],idB:[5,2]},{idA:[5,2],idB:[3,2]},{idA:[2,4],idB:[5,4]}],
    },
    { id: '5-19', world: 5, level: 19, name: 'Superposition',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,A,F,F,B,F,W],[W,F,F,E,W,F,F,W],[W,F,B,W,F,A,F,W],[W,F,F,E,F,F,F,W],[W,F,A,F,B,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,F,B,F,F,A,F,W],[W,F,F,W,E,F,F,W],[W,F,A,F,W,B,F,W],[W,F,F,F,E,F,F,W],[W,X,B,F,A,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [12,18,26],
        entanglements: [{idA:[3,2],idB:[4,2]},{idA:[3,4],idB:[4,4]}],
    },
    { id: '5-20', world: 5, level: 20, name: 'Superposition Mastery',
        gridA: [[W,W,W,W,W,W,W,W],[W,F,A,F,B,F,A,W],[W,F,E,W,F,E,F,W],[W,F,F,F,F,F,F,W],[W,F,B,F,W,A,F,W],[W,F,F,E,F,F,F,W],[W,F,F,F,F,F,X,W],[W,W,W,W,W,W,W,W]],
        gridB: [[W,W,W,W,W,W,W,W],[W,B,F,A,F,B,F,W],[W,F,E,F,W,E,F,W],[W,F,F,F,F,F,F,W],[W,F,A,W,F,B,F,W],[W,F,E,F,F,F,F,W],[W,X,F,F,F,F,F,W],[W,W,W,W,W,W,W,W]],
        startA: [1,1], startB: [6,1], collapseCharges: 0, par: [14,22,30],
        entanglements: [{idA:[2,2],idB:[5,2]},{idA:[5,2],idB:[2,2]},{idA:[3,5],idB:[2,5]}],
        tutorial: 'World 5 complete! Interference patterns await...',
    },
];
