// Phase Shift — World 3: Phase Walk
// Introduces Phase Gates — dimension-specific passability
// Phase gates encoded as 30 (permeable in A) or 31 (permeable in B)
// In dim A: tile 30 is walkable (like floor), tile 31 acts as wall
// In dim B: tile 31 is walkable (like floor), tile 30 acts as wall

import { LevelDefinition } from '../../types';

// Helper: F=0(floor), W=1(wall), X=5(exit), A=30(gate-A), B=31(gate-B)
const F = 0, W = 1, X = 5, A = 30, B = 31;

export const WORLD_03: LevelDefinition[] = [
    {
        id: '3-1', world: 3, level: 1, name: 'First Gate',
        gridA: [
            [W,W,W,W,W,W],
            [W,F,F,A,F,W],
            [W,F,F,F,F,W],
            [W,F,F,F,X,W],
            [W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W],
            [W,F,F,A,F,W],
            [W,F,F,F,F,W],
            [W,X,F,F,F,W],
            [W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [4, 1],
        collapseCharges: 0,
        par: [4, 7, 10],
        tutorial: 'Phase Gates glow teal. Gate "A" lets you pass in Dimension A but blocks in B.',
    },
    {
        id: '3-2', world: 3, level: 2, name: 'Gate Divide',
        gridA: [
            [W,W,W,W,W,W],
            [W,F,F,F,F,W],
            [W,F,B,F,F,W],
            [W,F,F,F,F,W],
            [W,F,F,F,X,W],
            [W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W],
            [W,F,F,F,F,W],
            [W,F,B,F,F,W],
            [W,F,F,F,F,W],
            [W,X,F,F,F,W],
            [W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [4, 1],
        collapseCharges: 0,
        par: [5, 8, 12],
        tutorial: 'Gate "B" lets you pass in Dimension B but blocks in A. Plan your route!',
    },
    {
        id: '3-3', world: 3, level: 3, name: 'Both Gates',
        gridA: [
            [W,W,W,W,W,W],
            [W,F,A,F,F,W],
            [W,F,F,F,F,W],
            [W,F,F,B,F,W],
            [W,F,F,F,X,W],
            [W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W],
            [W,F,A,F,F,W],
            [W,F,F,F,F,W],
            [W,F,F,B,F,W],
            [W,X,F,F,F,W],
            [W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [4, 1],
        collapseCharges: 0,
        par: [6, 9, 14],
    },
    {
        id: '3-4', world: 3, level: 4, name: 'Gate Corridor',
        gridA: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,A,W,F,W,B,W],
            [W,F,F,F,F,F,W],
            [W,F,F,F,F,X,W],
            [W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,A,W,F,W,B,W],
            [W,F,F,F,F,F,W],
            [W,X,F,F,F,F,W],
            [W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [5, 1],
        collapseCharges: 0,
        par: [6, 10, 14],
    },
    {
        id: '3-5', world: 3, level: 5, name: 'Phase Maze',
        gridA: [
            [W,W,W,W,W,W,W],
            [W,F,F,A,F,F,W],
            [W,F,W,F,W,F,W],
            [W,F,B,F,A,F,W],
            [W,F,W,F,W,F,W],
            [W,F,F,F,F,X,W],
            [W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W],
            [W,F,F,A,F,F,W],
            [W,F,W,F,W,F,W],
            [W,F,B,F,A,F,W],
            [W,F,W,F,W,F,W],
            [W,X,F,F,F,F,W],
            [W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [5, 1],
        collapseCharges: 0,
        par: [8, 12, 18],
    },
    {
        id: '3-6', world: 3, level: 6, name: 'One Way',
        gridA: [
            [W,W,W,W,W,W],
            [W,F,F,F,F,W],
            [W,A,A,A,F,W],
            [W,F,F,F,F,W],
            [W,F,F,F,X,W],
            [W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W],
            [W,F,F,F,F,W],
            [W,B,B,B,F,W],
            [W,F,F,F,F,W],
            [W,X,F,F,F,W],
            [W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [4, 1],
        collapseCharges: 0,
        par: [6, 9, 14],
    },
    {
        id: '3-7', world: 3, level: 7, name: 'Split Route',
        gridA: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,W,A,W,F,W],
            [W,F,A,F,B,F,W],
            [W,F,W,B,W,F,W],
            [W,F,F,F,F,X,W],
            [W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,F,W,A,W,F,W],
            [W,F,A,F,B,F,W],
            [W,F,W,B,W,F,W],
            [W,X,F,F,F,F,W],
            [W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [5, 1],
        collapseCharges: 0,
        par: [8, 13, 18],
    },
    {
        id: '3-8', world: 3, level: 8, name: 'Gate Box',
        gridA: [
            [W,W,W,W,W,W],
            [W,F,F,F,F,W],
            [W,F,2,F,F,W],
            [W,A,F,F,F,W],
            [W,F,F,F,X,W],
            [W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W],
            [W,F,F,F,F,W],
            [W,F,F,2,F,W],
            [W,F,F,F,A,W],
            [W,X,F,F,F,W],
            [W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [4, 1],
        collapseCharges: 0,
        par: [6, 10, 15],
        tutorial: 'Boxes interact with gates too. Push carefully!',
    },
    {
        id: '3-9', world: 3, level: 9, name: 'Winding Gates',
        gridA: [
            [W,W,W,W,W,W,W],
            [W,F,F,B,F,F,W],
            [W,F,W,F,W,F,W],
            [W,F,A,F,B,F,W],
            [W,F,W,F,W,F,W],
            [W,F,F,A,F,X,W],
            [W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W],
            [W,F,F,B,F,F,W],
            [W,F,W,F,W,F,W],
            [W,F,A,F,B,F,W],
            [W,F,W,F,W,F,W],
            [W,X,F,A,F,F,W],
            [W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [5, 1],
        collapseCharges: 0,
        par: [8, 13, 18],
    },
    {
        id: '3-10', world: 3, level: 10, name: 'Gate Walls',
        gridA: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,B,B,F,A,A,W],
            [W,F,F,F,F,F,W],
            [W,A,A,F,B,B,W],
            [W,F,F,F,F,X,W],
            [W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,B,B,F,A,A,W],
            [W,F,F,F,F,F,W],
            [W,A,A,F,B,B,W],
            [W,X,F,F,F,F,W],
            [W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [5, 1],
        collapseCharges: 0,
        par: [8, 12, 18],
    },
    {
        id: '3-11', world: 3, level: 11, name: 'Alternating',
        gridA: [
            [W,W,W,W,W,W,W,W],
            [W,F,A,F,B,F,F,W],
            [W,F,F,F,F,F,F,W],
            [W,F,B,F,A,F,F,W],
            [W,F,F,F,F,F,X,W],
            [W,W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W,W],
            [W,F,A,F,B,F,F,W],
            [W,F,F,F,F,F,F,W],
            [W,F,B,F,A,F,F,W],
            [W,X,F,F,F,F,F,W],
            [W,W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [6, 1],
        collapseCharges: 0,
        par: [7, 11, 16],
    },
    {
        id: '3-12', world: 3, level: 12, name: 'Gate Spiral',
        gridA: [
            [W,W,W,W,W,W,W,W],
            [W,F,F,F,F,F,F,W],
            [W,F,W,W,W,A,F,W],
            [W,F,W,F,F,F,F,W],
            [W,F,B,F,W,W,F,W],
            [W,F,F,F,F,F,F,W],
            [W,F,F,F,F,F,X,W],
            [W,W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W,W],
            [W,F,F,F,F,F,F,W],
            [W,F,A,W,W,W,F,W],
            [W,F,F,F,F,W,F,W],
            [W,F,W,W,B,F,F,W],
            [W,F,F,F,F,F,F,W],
            [W,X,F,F,F,F,F,W],
            [W,W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [6, 1],
        collapseCharges: 0,
        par: [10, 15, 22],
    },
    {
        id: '3-13', world: 3, level: 13, name: 'Narrow Phase',
        gridA: [
            [W,W,W,W,W,W],
            [W,F,F,F,F,W],
            [W,A,W,W,F,W],
            [W,F,F,F,F,W],
            [W,F,W,W,B,W],
            [W,F,F,F,X,W],
            [W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W],
            [W,F,F,F,F,W],
            [W,F,W,W,A,W],
            [W,F,F,F,F,W],
            [W,B,W,W,F,W],
            [W,X,F,F,F,W],
            [W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [4, 1],
        collapseCharges: 0,
        par: [7, 11, 16],
    },
    {
        id: '3-14', world: 3, level: 14, name: 'Cross Phase',
        gridA: [
            [W,W,W,W,W,W,W],
            [W,F,F,A,F,F,W],
            [W,F,W,F,W,F,W],
            [W,B,F,F,F,A,W],
            [W,F,W,F,W,F,W],
            [W,F,F,B,F,X,W],
            [W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W],
            [W,F,F,B,F,F,W],
            [W,F,W,F,W,F,W],
            [W,A,F,F,F,B,W],
            [W,F,W,F,W,F,W],
            [W,X,F,A,F,F,W],
            [W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [5, 1],
        collapseCharges: 0,
        par: [8, 13, 18],
    },
    {
        id: '3-15', world: 3, level: 15, name: 'Gate Labyrinth',
        gridA: [
            [W,W,W,W,W,W,W,W],
            [W,F,A,F,F,B,F,W],
            [W,F,W,F,W,F,F,W],
            [W,F,F,F,A,F,W,W],
            [W,W,F,W,F,F,F,W],
            [W,F,F,B,F,F,X,W],
            [W,W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W,W],
            [W,F,B,F,F,A,F,W],
            [W,F,F,W,F,W,F,W],
            [W,W,F,B,F,F,F,W],
            [W,F,F,F,W,F,F,W],
            [W,X,F,A,F,F,F,W],
            [W,W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [6, 1],
        collapseCharges: 0,
        par: [10, 15, 22],
    },
    {
        id: '3-16', world: 3, level: 16, name: 'Double Gate',
        gridA: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,A,F,W,F,B,W],
            [W,F,F,F,F,F,W],
            [W,B,F,W,F,A,W],
            [W,F,F,F,F,X,W],
            [W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W],
            [W,F,F,F,F,F,W],
            [W,B,F,W,F,A,W],
            [W,F,F,F,F,F,W],
            [W,A,F,W,F,B,W],
            [W,X,F,F,F,F,W],
            [W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [5, 1],
        collapseCharges: 0,
        par: [8, 12, 18],
    },
    {
        id: '3-17', world: 3, level: 17, name: 'Phase Channel',
        gridA: [
            [W,W,W,W,W,W,W,W],
            [W,F,F,F,F,F,F,W],
            [W,F,A,W,B,F,F,W],
            [W,F,F,F,F,F,F,W],
            [W,F,B,W,A,F,F,W],
            [W,F,F,F,F,F,X,W],
            [W,W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W,W],
            [W,F,F,F,F,F,F,W],
            [W,F,B,W,A,F,F,W],
            [W,F,F,F,F,F,F,W],
            [W,F,A,W,B,F,F,W],
            [W,X,F,F,F,F,F,W],
            [W,W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [6, 1],
        collapseCharges: 0,
        par: [9, 14, 20],
    },
    {
        id: '3-18', world: 3, level: 18, name: 'Gate Complex',
        gridA: [
            [W,W,W,W,W,W,W,W],
            [W,F,F,A,F,F,F,W],
            [W,F,W,F,W,B,F,W],
            [W,F,A,F,F,F,F,W],
            [W,F,F,W,B,W,F,W],
            [W,F,F,F,F,F,F,W],
            [W,F,F,F,F,F,X,W],
            [W,W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W,W],
            [W,F,F,B,F,F,F,W],
            [W,F,A,W,F,W,F,W],
            [W,F,F,F,B,F,F,W],
            [W,F,W,A,F,W,F,W],
            [W,F,F,F,F,F,F,W],
            [W,X,F,F,F,F,F,W],
            [W,W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [6, 1],
        collapseCharges: 0,
        par: [10, 16, 22],
    },
    {
        id: '3-19', world: 3, level: 19, name: 'Phase Gauntlet',
        gridA: [
            [W,W,W,W,W,W,W,W],
            [W,F,A,F,B,F,A,W],
            [W,F,F,W,F,W,F,W],
            [W,F,B,F,A,F,F,W],
            [W,W,F,W,F,W,F,W],
            [W,F,A,F,B,F,X,W],
            [W,W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W,W],
            [W,F,B,F,A,F,B,W],
            [W,F,W,F,F,W,F,W],
            [W,F,A,F,B,F,F,W],
            [W,F,W,F,W,F,W,W],
            [W,X,B,F,A,F,F,W],
            [W,W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [6, 1],
        collapseCharges: 0,
        par: [10, 16, 22],
    },
    {
        id: '3-20', world: 3, level: 20, name: 'Phase Mastery',
        gridA: [
            [W,W,W,W,W,W,W,W],
            [W,F,F,A,F,B,F,W],
            [W,F,W,F,W,F,F,W],
            [W,B,F,F,A,F,W,W],
            [W,F,W,F,W,F,F,W],
            [W,F,A,F,F,B,F,W],
            [W,F,F,F,F,F,X,W],
            [W,W,W,W,W,W,W,W],
        ],
        gridB: [
            [W,W,W,W,W,W,W,W],
            [W,F,F,B,F,A,F,W],
            [W,F,F,W,F,W,F,W],
            [W,W,F,A,F,F,B,W],
            [W,F,F,W,F,W,F,W],
            [W,F,B,F,F,A,F,W],
            [W,X,F,F,F,F,F,W],
            [W,W,W,W,W,W,W,W],
        ],
        startA: [1, 1], startB: [6, 1],
        collapseCharges: 0,
        par: [12, 18, 26],
        tutorial: 'World 3 complete! Entangled boxes await...',
    },
];
